### ISSUE TITLE
WARC revision 1.1 (clarification): validity of a WARC record with unknown field(s).

### ISSUE THREAD

**Issue by cleymour** [iipc/warc-specifications#9]
Definition: In 6.1 “WARC record types/General”, it is written “Because new record types that extend the WARC format may be defined in future standards, WARC processing software shall skip records of unknown type”.

However, it is not explained if a known record type with new named fields should be valid; and should be processed by WARC reading or validating tools.

Decision: it should be stated that it is allowed to add new named fields, as well as new records types. However, it is strongly recommended to discuss the utility and the relevance of these new named fields within the right forum (e.g. the IIPC for web archiving) and to inform the maintenance body of the standard (currently the ISSN International Centre). 

New named field that are considered relevant and mature by a large community of WARC users should be added in the next revision of the WARC standard.

Besides, the sentence “Because new record types that extend the WARC format may be defined in future standards…” should be replaced by “Because new record types that extend the WARC format may be defined in future versions of the standard…”.

Action: Clément Oury to propose a formulation.

**Comment by cleymour** [comment]
(1) Add in section 4 "File and record model", add to the list of defined fields
               | WARC-Future-type	; as defined by the concerned user community and the maintenance agency

**Comment by cleymour** [comment]
(2) Add at the end of section 4 (after "as specified in 8.3."):
"New records types and new named fields may be added in addition to the existing list. However, it is strongly recommended to discuss any addition before implementing it. Discussion should be held within the right forum (e.g. IIPC for web archiving) under the auspices of the maintenance agency of the standard.
New records types and new named fields agreed by the community of WARC standard users in the relevant domain should be mentioned in the further version of the WARC standard".

**Comment by cleymour** [comment]
(3) Rephrase the second sentence of 6.1 "General": 
"Because new record types that extend the WARC format may be defined in future versions of the WARC standard, WARC processing software shall skip records of unknown type".

**Comment by anjackson** [comment]
Wording should make it clear that this is a guideline to avoid collisions.

**Comment by saraaubry** [comment]
The following changes have been integrated in the revised ISO draft during the ISO working group meeting on November 16-17, 2015 : 

1/ Add in section 4 "File and record model":
New named fields and new records types may be defined in extensions of the core format. However, it is strongly recommended to discuss any addition to verify that a suitable field or type doesn't already exist to avoid collision. Discussion should be held within the right forum (e.g. the IIPC for web archiving) and the **maintenance agency**  of the standard should be informed of any addition to facilitate the future revision of the standard.

 **Check with ISO how to define maintenance agency.

2/ Delete in section 5.5 "Warc-Type" in the example " | future-type future-type=token".

3/ Rephrase the second sentence of 6.1 "General":
"Because new record types that extend the WARC format may be defined in future versions of the WARC standard, WARC processing software shall skip records of unknown type".

**Comment by saraaubry** [comment]
Included in WARC 1.1
